dist: xenial

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

# script - run the build script
script:
    - hugo -b /docs --environment production

# github pages master branch
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: develop  # branch contains Hugo generator code
